### ISSUE TITLE
PURL server login fails if PURL servers are behind Cloudflare

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#119]
This problem was discovered in our staging environment. The staging PURL server was put behind Cloudflare. After doing so, attempts to create ontologies and submissions at stage.bioontology.org started failing with 500 errors. Tracked the underlying exception down in the unicorn.std.err file on ncbostage-rest2.stanford.edu:

```
2021-06-23 13:43:02 - NoMethodError - undefined method `split' for nil:NilClass:
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-71a5ca8f7574/lib/ontologies_linked_data/purl/purl_client.rb:17:in `purl_server_login'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-71a5ca8f7574/lib/ontologies_linked_data/purl/purl_client.rb:27:in `create_purl'
	/srv/ncbo/ontologies_api/shared/bundle/ruby/2.6.0/bundler/gems/ontologies_linked_data-71a5ca8f7574/lib/ontologies_linked_data/models/ontology.rb:409:in `save'
	/srv/ncbo/ontologies_api/releases/20210619061350/controllers/ontologies_controller.rb:148:in `create_ontology'
	/srv/ncbo/ontologies_api/releases/20210619061350/controllers/ontologies_controller.rb:49:in `block (2 levels) in <class:OntologiesController>'
```

**Comment by jvendetti** [comment]
This change to the infrastructure was reverted, i.e., the staging PURL server is no longer behind Cloudflare. New ontology and submission creation is working again in staging. The desire is to address this issue at some point in the future.

**Comment by alexskr** [comment]
relates to #169

**Comment by alexskr** [comment]
PURLZ server is deprecated
https://github.com/ncbo/bioportal-project/issues/379
